version: "3"

services:
  node:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "7545:8545"
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'gun concert fault upgrade world midnight sleep rough sick collect noodle want'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'

