name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 15.x

      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Install app modules
        run: cd app && npm install

      - name: Lint Solidity Files
        run: npm run lint:sol

      - name: Lint JavaScript Files
        run: npm run lint:js

      - name: Compile
        run: npm run compile --force
