name: Release

on:
  push:
    branches:
      - trunk
    tags:
      - 'v*' # Push events to matching v*, e,g, v0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Deploy
        run: npm run deploy
