name: Wallfair. Smart Contract Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Install Truffle
        run: npm install truffle -g
      - name: Run tests
        run: truffle test --network test
